default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: username
  password: 'password'

development:
  <<: *default
  database: reporting_development

test:
  <<: *default
  database: reporting_test

production:
  <<: *default
  database: reporting_production